### ISSUE TITLE
Increase contrast of selected items in process list

### ISSUE THREAD

**Issue by koteq** [processhacker2/processhacker#105]
I know that selected items in lists are styled according to current system theme but it would be great if there was an option to increase contrast somehow. It may be done in many different ways. Bold font or custom selection color or even outline.

![Example of System process being selected in Windows 10](https://i.imgur.com/i9Z05QH.png)
Here's an example of my current setup on Windows 10 with System process selected.

**Comment by dmex** [comment]
The nightly build includes a new setting called TreeListCustomColorsEnable for dark selection colors (e.g. TreeListCustomColorsEnable = 1) 👍

**Comment by lollita** [comment]
If I use
```
  <setting name="TreeListCustomColorsEnable">1</setting>
  <setting name="TreeListCustomColorText">ff0000</setting>
  <setting name="TreeListCustomColorFocus">ff0000</setting>
  <setting name="TreeListCustomColorSelection">ff0000</setting>
```

only intial background remove but not apply red
