### ISSUE TITLE
Missing file handles for disk/volumes?

### ISSUE THREAD

**Issue by pbatard** [processhacker2/processhacker#131]
This was tested using Process Hacker 2.39 (x64) on Windows 10 x64 Build 15063 (Creators Update).

Basically, I've been looking into possible means of identifying what process is monopolizing which disk handle for my [Rufus](https://github.com/pbatard/rufus) formatting utility, and as such, I've been trying to see if Process Hacker could be of help.

One thing I am noticing however is that it currently does not seem to be listing some handles that processes may have opened for disks/volumes.

This issue can be replicated by performing the following (using [HxD](https://mh-nexus.de/en/hxd/) as a volume "hogging" process, but this can probably be demonstrated with other apps).
1. Download and run [HxD](https://mh-nexus.de/en/hxd/) as Administrator.
3. Go to _Extras_ &rarr; _Open disk..._ and open a logical drive in read-only mode.
4. As pointed out by SysInternal's Process Explorer (running elevated), this results in HxD keeping a handle to `\Device\HarddiskVolume##` opened:
![image1](https://cloud.githubusercontent.com/assets/1206968/25410771/a72e751e-2a10-11e7-9027-448a51c94f42.png)
5. Now run ProcessHacker (as Administrator) and look for the handles associated with the `HxD.exe` process. `\Device\HarddiskVolume##`  is not being listed:
![image2](https://cloud.githubusercontent.com/assets/1206968/25410802/dab7965e-2a10-11e7-999d-f93d161bf1f6.png)

Performing a search for the handle in Process Hacker also returns no results.

Am I missing something about looking for a disk/volume handle in Process Hacker, or is this a known limitation?

**Comment by dmex** [comment]
Process Hacker converts native NT file paths (e.g. \Device\HardDiskVolume10) to Win32 paths (e.g. D:\\) for ease of use and convenience. 

You need to right-click the column headers on the Handles tab and add the "Original name" column to see the original untranslated file object names: http://i.imgur.com/dskBluj.png

I think the problem is that you couldn't search for the object name and that it should have been possible to search for names such as  \Device\HardDiskVolume10 on the find handles window or would you prefer using the mounted volume names such as D:\\?


>Note: You should be running a nightly build if you're using Windows 10 creators update. They're the only releases currently supporting Windows 10:
https://wj32.org/processhacker/nightly.php

**Comment by pbatard** [comment]
Aha! That makes sense. Original Name does list the handle, so all's good.

You are correct that my main issue was that I couldn't find any hits for `\Device\HardDiskVolume10` when searching for it, so I assumed it was missing rather than listed under a different name.

Personally, I'd prefer if Process Hacker also gave hits when looking for the original name (especially as it will list `\Device\HardDiskVolume10` in the _Name_ column if the volume is in use, but not mounted in Windows), but the call is really up to you. For one thing, I was only looking into this with the goal of reusing part of Process Hacker's code for handle lookup in my application, which I'll modify to fit my specific needs. Plus, this should only matter for users looking up handle names that they obtained from another application, rather than cross referencing from Process Hacker.

Feel free to close this issue if you want then.

PS: Nightly build works great!

**Comment by VictorVG** [comment]
@**pbatard** 

WinNT use arc notation like UNIX famaly OS for disk names _bus\port\dev\partion_ starting WinNT 3.1 and have tow variants - SCSI and ATAPI. SCSI _bus\port\LUN\disk|partition_ and ATAPI _bus\port\dev\partion_ then used SCSI drive IO model virtuality HAL.

**Comment by sapoberse** [comment]
Hello bro if you want to hack user instagram account if can please help thank you

**Comment by TETYYS** [comment]
im not your friendo

**Comment by sapoberse** [comment]
If I can pay how much for you

**Comment by sapoberse** [comment]
halo

**Comment by TETYYS** [comment]
yes please pay me

**Comment by sapoberse** [comment]
Want 50 dollars or 60.12

**Comment by TETYYS** [comment]
reported

**Comment by dmex** [comment]
3 months later... I've finally updated the find handles window:

* Added treelist control
* Added column customization 
* Added object address column
* Added origin name column
* Added extra copy menus
* Fixed searching for the hexadecimal handle address (previously only searched the object address and not the handle address)
* Fixed window threading (previously shared the main window thread)
* Fixed resource usage (previously when you closed the window the results would not be freed which increased the overall Process Hacker memory usage)

@pbatard 

Can you update to the latest nightly build (Help > Check for Updates) and try searching for 'original names' such as Device\HardDiskVolume and let me know if it's what you would expect (and no crashes)? 😃

**Comment by pbatard** [comment]
Very nice!

Just tested a similar search to the one I had an issue with, using the latest nightly, and got the process that had my handle open without issues. Oh, and everything looks good on a High DPI display... 👍

**Comment by dmex** [comment]
Thanks, I'll close the ticket now it's implemented and working as expected 😃
