### ISSUE TITLE
Process time being seriously underreported

### ISSUE THREAD

**Issue by robertroessler** [processhacker2/processhacker#156]
PH 3.0.778 built locally under vs2017 as x64, running on Win 10 Pro x64.  Hardware details: Kaby Lake i7-7700 on Gigabyte Z270 board, 32 GB.

I have been seeing this for awhile and already reported it through email, but as there have been a number of updates that didn't address this, I wanted to bring it up once more.

Simply, on the process Properties sheet, "Statistics" tab: unless I don't understand what is supposed to be displayed here, I would think that a "CPU Cycles" count exceeding 4e9 (**not** a 2^32 issue, shows pretty much right away, just more obvious with a high cycle count) should be claiming more than "0.031" for each of Kernel and User times (or the Total of "0.062").

**Comment by dmex** [comment]
1) Does Process Explorer have the same behavior and show the same values?

2) Have you tried enabling/disabling the View menu > "Show CPU below 0.01" option for using cycle based calculation?

**Comment by robertroessler** [comment]
1. It does indeed [show the same values]...
2. I normally don't use that option, tried and left it running for a number of hours, no change to the reported "summary" stats...

So, what are we saying here?  Windows' own per-process data doesn't have adequate resolution to deal with small amounts of CPU usage?  It's all a round-off error? ;)

In any case, after spot-checking a number of relatively low-activity processes both PE and PH, I see that both certainly report the same values... and that both sometimes are seriously under-reporting, and sometimes both appear to get it "right".  

When I say "right", I am looking at the "Cycles" value, and computing a range of believable CPU times - based on my CPU's low-power clock of 800 MHz and performance clock of 4.2 GHz - and seeing if the reported figures are in that range... is there an obvious flaw in my methodology or expectations?

Given the agreement between PE and PH, we *could* say there is no "bug" here, or at least not an unexpected one...

Thanks for considering my report.

**Comment by dmex** [comment]
> Windows' own per-process data doesn't have adequate resolution to deal with small amounts of CPU usage? It's all a round-off error? ;)

Not too sure why but some hardware (and drivers) can cause that problem... As a rule we check Process Explorer and Task Manager and if they're the same value then it's considered accurate.
