### ISSUE TITLE
feature request: checkbox option to choose termination of process without confirmation

### ISSUE THREAD

**Issue by mailinglists35** [processhacker2/processhacker#158]
currently (including latest nightly v3) terminating a process requires confirmation
I need to be able to terminate a process without additional confirmation dialog window.

**Comment by dmex** [comment]
Have you tried the Options window > Advanced tab > untick Enable warnings?

**Comment by mailinglists35** [comment]
i've been there but I didn't figure out what it means. 'confirmation prompts' sounds more intuitive to me.
