### ISSUE TITLE
Restore Wikipedia page

### ISSUE THREAD

**Issue by dmex** [processhacker2/processhacker#161]
This ticket is for tracking restoration of the Process Hacker wikipedia page. 

The wikipedia page for Process Hacker deleted by wikipedia administrators... The admin I spoke with refused to restore the original page citing 'policy' and informed me that we need to republish the entire page and this will need to be done from scratch since I can't find any copies of the original page. 😠 

The deleted wiki page for Process Hacker:
https://en.wikipedia.org/wiki/Process_Hacker

The russian version of the page is still available but doesn't contain any of the original references or other information: 
https://ru.wikipedia.org/wiki/Process_Hacker

This page shows a screenshot of Process Hacker on the right hand side of the page but doesn't actually list Process Hacker under the "Common task managers" content section:
https://en.wikipedia.org/wiki/Task_manager

This page contains a dead link and incorrectly describes the usage of the Process Hacker anti-rootkit functionality: https://en.wikipedia.org/wiki/Rootkit

The revision history for all these pages no longer mentions Process Hacker anywhere (since the original page was deleted) making restoration difficult and additionally the wayback machine does not index Wikipedia... 

TODO:
- [ ] Research project references for new page (some references no longer exist and have been lost forever).
- [ ] Recreate wikipedia page template.
- [ ] Submit new wikipedia page.

**Comment by TETYYS** [comment]
Added Process Hacker under "Common task managers"

why do russians like PH so much?

**Comment by dmex** [comment]
> Added Process Hacker under "Common task managers"

Thanks 👍 

> why do russians like PH so much?

Telemetry from download statistics show the United States as having 40% more downloads than everywhere else 😄 

I actually asked few Russians about why they're using Process Hacker some time ago (considering we only release an english version and no translations) and this is more or less how they view the problems today and why they're using it:

> Western countries depend upon Antivirus software to protect their machines and have complete trust in that software but AV software is completely automated, closed source, bloatware that does everything secretly plus you have zero control over what it's doing on your machine or what it's checking and _always_ misses something. AV software also can't do anything at all about 0-day attacks or things that they don't yet know about yet which defeats the entire purpose of using AV software in the first place.
> 
> Russians don't trust western software (or even their own software for good reason) and Process Hacker has a few major differences that make it a much better alternative to AV software such as being open-source and instead of keeping details about your system secret Process Hacker shows you everything about your system instead and lets you determine what to check and what action to take instead of relying upon someone else to make those decisions for you.
> 
> Processes, services, network connections, disk activity, firewall activity, thread stacks, loaded modules, signatures, memory, handles... everything you see included in Process Hacker is something antivirus software scans secretly in the background and never shows you or lets you check yourself and you have zero ability to check your system manually for anything that bypassed your AV software and infected your machine - you can't even use your AV software to remove malicious software until it's 'detected' (and by then it's already too late) which is in stack contrast to everything included with Process Hacker.

> 
> AV software is completely useless these days and regularly can't detect most threats and other dangerous software and so you need tools like Process Hacker to perform your own 'scans' by viewing modules, checking memory, checking thread stacks or network connections etc... and that's why Russians love it because they can dump proprietary closed source AV software and handle their own security and make changes to the source-code without having to wait for someone else to protect their machine from various threats and attacks.

A lot of the features that have been added to Process Hacker are things that we're personally using to check parts of the system for malicious software - most people look at Process Hacker as a clone of Process Explorer and only useful for terminating processes or checking CPU usage but that's not quite  accurate and Process Hacker is more designed more for security purposes than anything else - almost every feature can be used to detect and remove malicious software and you're the one who makes the decision about what's malicious and what needs to be done about it (for example the Terminator feature).

If you know what you're doing and know how to handle threats or determine what's malicious then it makes a lot of sense to use tools like Process Hacker and check things yourself and make your own decisions about what to do about it than leaving it up to someone else and having zero control.

**Comment by diversenok** [comment]
[Kiwix](http://wiki.kiwix.org/wiki/Main_Page/en) provides offline Wikipedia dumps, so it can be useful here. But even a cursory glance shows that it wouldn't be so easy to find a dump from 2012. I checked 2017-01 and 2016-05, and of course with no result. I'll try to find such a dump in torrents and DC++. May be you know, when this article appeared (at least approximately)? And am I right that it was deleted in May 2012?

**Comment by dmex** [comment]
The admin voted for deletion in 2012 but it wasn't actually removed from the archive until sometime in 2014 and there's still a (partial) record of the conversation I had with the admin on their talk page about it.

I also didn't bother creating a ticket to track the issue at the time since the page was locked to prevent anyone from recreating it... I recently noticed the lock was removed so I created the ticket to track the restoration.

The Russian version of the page has remained available the entire time and I don't understand why it was only the English version of the page that was deleted (and locked) while also leaving all other references elsewhere on the site untouched... How do you get away with that behavior? 😕
