### ISSUE TITLE
Please add ability to limit processes by windows container

### ISSUE THREAD

**Issue by artisticcheese** [processhacker2/processhacker#162]
Those will be sharing the same JobID. Surprisingly TaskManager can do it out of the box.
![image](https://user-images.githubusercontent.com/13176884/28749371-b3227086-748a-11e7-9a58-40828c182db8.png)

**Comment by dmex** [comment]
The latest nightly build now includes the "Job Object ID" column:
https://wj32.org/processhacker/nightly.php
