### ISSUE TITLE
write read&write disk activity of process to file?

### ISSUE THREAD

**Issue by heforfree** [processhacker2/processhacker#164]
if possible add option to log desired desk activity of process to file
example log all disk activity of Firefox to file  
firefox.exe path of file readed type read
firefox.exe path of file write  type write

thanks best regards

**Comment by TETYYS** [comment]
use procmon for this

**Comment by heforfree** [comment]
no hard to get that program
i don't like that process hacker is better for me
in process hacker in Disk tab we have very easy understandable we can see activity
but can not save so it just one step forward for this feature
thanks

**Comment by dmex** [comment]
The disk tab doesn't show disk activity for some processes such as the Subsystem for Linux... You will need to use procmon.
