### ISSUE TITLE
View -> Windows does nothing

### ISSUE THREAD

**Issue by TETYYS** [processhacker2/processhacker#165]
On 3.0.651 and Window Explorer 1.6.0.0 pressing View -> Windows does nothing, just closes the View context menu.

**Comment by dmex** [comment]
3.0.683 works fine here?

**Comment by TETYYS** [comment]
windows 8.1 btw

**Comment by dmex** [comment]
I checked 8.1 and the windows option works fine... Are you creating PH on a separate desktop or using a job object to restrict window access or something?

**Comment by TETYYS** [comment]
nope..

**Comment by dmex** [comment]
If you can repro or debug it then reopen the ticket 👍

**Comment by TETYYS** [comment]
I can reproduce it every time, but I'll let you know when I'll debug it

**Comment by dmex** [comment]
Try removing strings for that window dialog in the WindowExplorer.RC file and rebuilding the plugin. If the window shows up then it's a control causing the dialog to fail... Also try commenting out the entire message loop for that window.

**Comment by dmex** [comment]
I fixed a memory corruption bug the other day... more than likely related 👍
