### ISSUE TITLE
Network Tools windows should use fixed-width font

### ISSUE THREAD

**Issue by David-Hari** [processhacker2/processhacker#175]
...or use tabs instead of spaces to separate columns of information (e.g. the time columns in trace route).
Otherwise the information is mis-aligned and harder to read.

**Comment by dmex** [comment]
Have you tried the latest nightly build?

**Comment by David-Hari** [comment]
I have not. If the problem has already been fixed then feel free to close this issue.

**Comment by dmex** [comment]
You can install the nightly version side-by-side with the latest stable version... If you can try out the latest nightly build and let me know if the NetworkTools changes are what you expect then it would help?

https://wj32.org/processhacker/nightly.php
