### ISSUE TITLE
Column sets

### ISSUE THREAD

**Issue by ferenczy** [processhacker2/processhacker#180]
I have a feature request: **please implement _column sets_**.

**What's the _column set_:** it's a saved list of columns for the main process list and their configuration (order, width), identified by a name. Basically, it means to have a possibility to save the current column set under some name and also have a possibility to switch between the saved sets, modify and delete them.

You can see how it looks in [Process Explorer](https://docs.microsoft.com/en-us/sysinternals/downloads/process-explorer): The configuration of columns is very similar to _Process Hacker_ - just right click on the process list columns header and select _Select columns..._. In addition to that, there are 3 more options in the _View_ menu:
- _Organize Column Sets..._ (allows to rename and delete the column sets)
- _Save Column Set..._ (allows to save the current column set and set a name of it)
- _Load Column Set..._ (allows to load a column set identified by a name)

**The motivation:** I'm using _Process Hacker_ usually for one of two purposes:
- debugging some problem - for such purpose I usually need many various columns
- killing a hang application - here I usually need only a very few columns. Actually, when I need to kill an application, the system is often overloaded or not in a good shape, so ideally, I need to load as few columns as possible.

Currently, as I cannot switch between various sets of columns (e.g. "minimal" and "full"), I have _Process Hacker_ configured to show all columns I may need for any purpose. That also means it takes some time to start _Process Hacker_ and it also uses more resources. This is causing problems when the system is not in a good shape, for example when there's an application which is causing the processor to spike at 100 %. In such state, I'm usually not able to even start _Process Hacker_, it shows the window, but it's not usable. I usually have to kill the problematic application using _Windows Task Manager_ or _Process Explorer_. When I do it, _Process Hacker_ suddenly becomes responsive.

I guess when I would have _Process Hacker_ configured to start with a minimal set of columns, I wouldn't have such issue.

**Comment by dmex** [comment]
Done. Column sets are available in the nightly builds 👍 
https://wj32.org/processhacker/nightly.php

>  In such state, I'm usually not able to even start Process Hacker, it shows the window, but it's not usable.

It'll help to disable signature verification using the Options > General tab > Uncheck the 'Check images for digital signatures' option.

I'm going to try implement custom signature verification at some point that should help with those startup performance issues when the system is under heavy lead.
