### ISSUE TITLE
Why is the minimum platform toolset set so high?

### ISSUE THREAD

**Issue by sgeto** [processhacker2/processhacker#182]
Please? 🙏 
The latest release is from more than a year ago.

Thanks

**Comment by sgeto** [comment]
lol nevermind.
I didn't see the nightly link in the readme.

But I have one more complain:

Why is the minimum platform toolset set so high?
I could very well work with VS2015 (update 3)

**Comment by dmex** [comment]
VS2015 is deprecated and not forwards compatible with Windows 10 or compatible with major security features such as CFG.

The entire project is designed to work out-of-the-box with any default installation of Visual Studio 2017... At minimum you only need to install the 'MsBuild' component or the Build Tools for Visual Studio 2017 (https://go.microsoft.com/fwlink/?linkid=840931) - you can select the absolute minimum of packages and  build the project using the \build\build_release.cmd script.

Its also a lot easier to maintain the project using the latest toolset and the alternative is spending hours/days backporting and re-implementing CRT/SDK/WDK functionality just for VS2015 when it's already in the latest toolset -  making stuff work with vs2015 is just a waste of development time.

**Comment by sgeto** [comment]
Thanks for clarifying.
One more thing:
Could you build the Nightly Builds with debugging infos? That would be helpful.

**Comment by dmex** [comment]
> Could you build the Nightly Builds with debugging infos? That would be helpful.

You'll need to create your own local build for debugging. Release symbols could be abused to bypass security restrictions and as such are not publicly available.

**Comment by sgeto** [comment]
last question (promise):
what options should pass to the CustomBuildTool to build it debug mode?

**Comment by dmex** [comment]
just run the build_debug.cmd script located in the \Build\ directory and it'll launch CustomBuildTool with the correct parameters 👍
