### ISSUE TITLE
Untrusted instead of AppContainer

### ISSUE THREAD

**Issue by MrX-at-GitHub** [processhacker2/processhacker#183]
On Windows 8.1 x86, Process Hacker shows chrome.exe processes an integrity level of Untrusted instead of AppContainer.

**Comment by dmex** [comment]
AppContainers are unrelated to Integrity labels so why should Process Hacker show 'AppContainer' instead of the integrity label value (e.g. Untrusted) ?

Chrome also doesn't use the AppContainer infrastructure and chrome processes don't have any AppContainer SIDs in their process token.

**Comment by ionescu007** [comment]
Dmex is right, that's actually a 'bug' in Process Explorer.

However here's an actual bug, for a Chrome process, PE shows the NULL SID
correctly/restricted, while PH does not.

Best regards,
Alex Ionescu

**Comment by MrX-at-GitHub** [comment]
> Chrome also doesn't use the AppContainer infrastructure and chrome processes don't have any AppContainer SIDs in their process token.

Then what is this?
Enable AppContainer Lockdown, chrome://flags/#enable-appcontainer

**Comment by ionescu007** [comment]
A non-default option :) But still, the integrity level is 'untrusted', not
'low' and not 'appcontainer', even if you enable that option.

Best regards,
Alex Ionescu

**Comment by MrX-at-GitHub** [comment]
> A non-default option :) But still, the integrity level is 'untrusted', not
'low' and not 'appcontainer', even if you enable that option.

Thanks Alex. Thanks for such an important person answers directly to me, your reputation precedes you, lol.

Best regards.

**Comment by MrX-at-GitHub** [comment]
Also, thank you @dmex

**Comment by MrX-at-GitHub** [comment]
One more question, does this information applies on Windows 10 too?

**Comment by dmex** [comment]
Yep it's the same on Windows 10.

@ionescu007 
The NULL SID (restricted) issue was fixed by @kobykahane a few weeks ago in the nightly branch 👍
