### ISSUE TITLE
long command line tooltip problem

### ISSUE THREAD

**Issue by tigros** [processhacker2/processhacker#194]
Hi guys,

There's an issue with long "Command line" main window tooltips causing dwm/uxsms or aero in other words to crash and restart, this on win7x64.

You would need a command line of 3000+ chars to reproduce, maybe something else not sure.

Anyway fixed it by changing line 5825 of treenew.c it says:
getCellTooltip.MaximumWidth = -1;
so put
getCellTooltip.MaximumWidth = 650;

 best!

**Comment by dmex** [comment]
> You would need a command line of 3000+ chars to reproduce

If anything the commandline probably includes an illegal character because the length is truncated to 1000 characters: PhEllipsisString(Process->CommandLine, 100 * 10);

See PhGetProcessTooltipText line 128:  https://github.com/processhacker2/processhacker/blob/master/ProcessHacker/itemtips.c#L124

> MaximumWidth = 650;

The maximum length is 32767?

**Comment by tigros** [comment]
yes ur right it's more about content than length, it was more like 1500 too i was looking in the debugger and that's unicode.

that 650 is for display width afaik not length of data.

here's an example command line that causes aero crash:

"C:\Program Files (x86)\Adobe\Acrobat Reader DC\Reader\AcroCEF\RdrCEF.exe" --type=renderer --primordial-pipe-token=8F939968BD7AEEAD8FFC2898905885DD --lang=en-US --disable-pack-loading --lang=en-US --log-file="C:\Program Files (x86)\Adobe\Acrobat Reader DC\Reader\AcroCEF\debug.log" --log-severity=disable --product-version="ReaderServices/18.9.20044 Chrome/59.0.3071.15" --enable-pinch --device-scale-factor=1.25 --num-raster-threads=4 --enable-main-frame-before-activation --content-image-texture-target=0,0,3553;0,1,3553;0,2,3553;0,3,3553;0,4,3553;0,5,3553;0,6,3553;0,7,3553;0,8,3553;0,9,3553;0,10,3553;0,11,3553;0,12,3553;0,13,3553;0,14,3553;0,15,3553;0,16,3553;1,0,3553;1,1,3553;1,2,3553;1,3,3553;1,4,3553;1,5,3553;1,6,3553;1,7,3553;1,8,3553;1,9,3553;1,10,3553;1,11,3553;1,12,3553;1,13,3553;1,14,3553;1,15,3553;1,16,3553;2,0,3553;2,1,3553;2,2,3553;2,3,3553;2,4,3553;2,5,3553;2,6,3553;2,7,3553;2,8,3553;2,9,3553;2,10,3553;2,11,3553;2,12,3553;2,13,3553;2,14,3553;2,15,3553;2,16,3553;3,0,3553;3,1,3553;3,2,3553;3,3,3553;3,4,3553;3,5,3553;3,6,3553;3,7,3553;3,8,3553;3,9,3553;3,10,3553;3,11,3553;3,12,3553;3,13,3553;3,14,3553;3,15,3553;3,16,3553;4,0,3553;4,1,3553;4,2,3553;4,3,3553;4,4,3553;4,5,3553;4,6,3553;4,7,3553;4,8,3553;4,9,3553;4,10,3553;4,11,3553;4,12,3553;4,13,3553;4,14,3553;4,15,3553;4,16,3553 --disable-accelerated-video-decode --disable-webrtc-hw-vp8-encoding --disable-gpu-compositing --service-request-channel-token=8F939968BD7AEEAD8FFC2898905885DD --renderer-client-id=2 --mojo-platform-channel-handle=1368 --allow-no-sandbox-job /prefetch:1

**Comment by dmex** [comment]
Can't reproduce any issues with commandlines and aero.

> command line that causes aero crash

You probably something installed that's injecting/hooking/modifying dwm.
