### ISSUE TITLE
Memory leak when running PH under Administartor

### ISSUE THREAD

**Issue by skipik** [processhacker2/processhacker#195]
I'm using 3.0.5636.1109, KPH driver is always on. PH process takes 300-500 mb if I run it with admin privileges. If you want to repro this situation just run the programm as admin and leave it for 3-5 hours.

It doesn't happen if I run it with double click btw (just "+" at the top of window).

Let me know if you need more info.

Windows 10 v1709 (x64), Process Hacker 3.0.5636.1109 + Extra Plugins.

**Comment by dmex** [comment]
Its an issue with how some ExtraPlugins have been implemented. You should disable any installed extra plugins and create the issue over there: https://github.com/processhacker2/plugins-extra/issues
