### ISSUE TITLE
Feature Request: Escape while filter is set

### ISSUE THREAD

**Issue by cpriest** [processhacker2/processhacker#196]
Just a minor feature request.  I'd like it if, when I have a filter set and press escape it clears the filter instead of closing.  If the filter is already clear, then escape would close the window.

Thanks!

**Comment by dmex** [comment]
The escape key is handled by the dialog manager and most users expect it'll close the window instead of clearing the searchbox and having to press it twice. I could make this an optional setting that overrides the behaviour but having a specific key would be better (e.g. CTRL+D)?
