### ISSUE TITLE
Found KProcessHacker3 the "Stop pending" problems on Win 7 SP1 x64 (problem can have local source???).

### ISSUE THREAD

**Issue by VictorVG** [processhacker2/processhacker#197]
Found KProcessHacker3 the "Stop pending" problems on Win 7 SP1 x64 (problem can have local source???).

Summary:

Driver KProcessHacker3 can friezes then stopped or restart operation in to
"Stop pending" state.

Synopsis:

Process Hacker display driver status "Stop pending" in to Services tab and
have problems then don't see Job tabs for job process proprieties in
v3.0.5645.1118 (detection time) - v3.0.5660.1123.

Step fo responds:

Service Control Manager (SCM) console log (I use SC command on CMD console for diagnose this
problem). Problem's found on three independence computers after update (in to
Pascal code for Inno Setup installer I temporary added workaround for this
problem's).
```
Time + 00:00:00

sc query KProcessHacker3

ServiceName: KProcessHacker3
        Type:                 1 KERNEL_DRIVER
        Condition:            4 RUNNING
                              (STOPPABLE, NOT_PAUSABLE, IGNORES_SHUTDOWN)
        Win32 exit code:      0 (0x0)
        Service_Service_Code: 0 (0x0)
        Control_point:        0x0
        Waiting:              0x0

Time + 00:01:00

sc stop KProcessHacker3

Time + 00:01:30

sc query KProcessHacker3

ServiceName: KProcessHacker3
        Type:                 1 KERNEL_DRIVER
        Status:               3 STOP_PENDING
                              (STOPPABLE, NOT_PAUSABLE, IGNORES_SHUTDOWN)
        Win32 exit code:      0 (0x0)
        Service_Service_Code: 0 (0x0)
        Control_point:        0x0
        Waiting:              0x0

Time + 00:02:00

sc stop KProcessHacker3

[SC] ControlService: error: 1061:

The service is currently unable to receive commands.

Time + 00:03:00

sc query KProcessHacker3

[SC] StartService: Error: 1056:

One copy of the service is already running.

Time + 00:03:30

sc querex KPRocessHacker3

ServiceName: KProcessHacker3
        Type:                 1 KERNEL_DRIVER
        Status:               3 STOP_PENDING
                              (STOPPABLE, NOT_PAUSABLE, IGNORES_SHUTDOWN)
        Win32 exit code:      0 (0x0)
        Service_Service_Code: 0 (0x0)
        Control_point:        0x0
        Waiting:              0x0
        ID_process: 0
        Flags:

```

Also I attached this log for works - [KPRocessHaker3.txt](https://github.com/processhacker2/processhacker/files/1529275/KPRocessHaker3.txt)

**Comment by dmex** [comment]
I have no idea what you're talking about.

**Comment by VictorVG** [comment]
I ran into the fact that when I started PH after the update I did not see in the properties of the Job tab running as the Job process. I began to look that with the driver - on the Services tab PH displays its status as "Stop pending". First, I tried to restart the driver through the PH - I can not, through the Far Service Manager plugin, also messages about the impossibility to perform the operation.

I checked it on another machine with Win7 SP1 (installed with MSDN image) and all updates where Process Hacker was not previously installed (it was put on the stand as the first and only application) - with a probability of 0.5 - 0.6 after running Inno Setup driver does not start. I began to look at the reasons - in the section [CODE] of the script I had the code:

```
procedure CurStepChanged (CurStep: TSetupStep);
var
  iResultCode: Integer;
begin
  if CurStep = ssInstall then begin
    if IsServiceRunning ('KProcessHacker2') then
      StopService ('KProcessHacker2');
    if IsTaskSelected ('delete_KPH_service') then
      RemoveService ('KProcessHacker2');
    if IsServiceRunning ('KProcessHacker3') then
      StopService ('KProcessHacker3');
  end;
```
whose task is to temporarily stop the driver so that the installation can overwrite it. And since the phenomenon was reproduced on three different machines, I decided to first disable the use and remove the driver through the command `ProcessHacker -uninstallkph` with the OS reboot. And then it got out that after the restart the driver is not deleted, and SCM reports that it is marked for deletion. I restarted the OS again, rechecked the driver status via the sc query KProcessHacker3 and got the status of "Stop pending".

As normal I see:

![1](https://user-images.githubusercontent.com/906886/33692050-8091be46-dafc-11e7-92bb-f643da127bae.png)

Then problem I see:

![2](https://user-images.githubusercontent.com/906886/33692263-6ed563be-dafd-11e7-8ac3-2de394c56f24.png)

???????

Then I restarted the machine again with the power turned off and checked the driver status after the OS startup process - there is, and its status is "Stop pending". I deleted the driver manually, cleaned all its entries in the Registry, restarted the machine, made sure that there was no driver, installed PH again - the driver works. Uploaded the PH, waited for the completion of its task, put it on top as an update - the driver is in the "Stop pending" state and after restarting the OS does not start.

That's why I asked for help - I can not understand what could cause such strange OS behavior and how to fix it?

There is an idea to add to the script code the command to start the driver and check its success and bind to it the launch of Process Hacker at the end of the installation, but is it worth it? Just in case, here are the installation script codes (old and current). I am now completely deadlocked and will be happy with any clue to get out of it.

I used Inno Setup scripts [**installer_current.zip**](https://github.com/processhacker2/processhacker/files/1537312/installer_current.zip) and current whats try fix this problems [**installer_old.zip**](https://github.com/processhacker2/processhacker/files/1537313/installer_old.zip).

**Comment by TETYYS** [comment]
I had Stop pending state on KPH3 driver too when I tried to stop it manually. Just had to exit and start PH again and it deleted normally.

**Comment by dmex** [comment]
> I tried to restart the driver through the PH - I can not

You can't stop drivers while applications still have open handles. Close Process Hacker before stopping the driver.

> I used Inno Setup scripts

I'm not going to fix legacy code that was deprecated and removed from the repository... You're going to have to use the newer CustomSetupTool.

**Comment by VictorVG** [comment]
The idea of what to do understood. Thanks for the tips! I'll think about how to get around Inno Setup errors - it looks like it's their source. Not just so I use NSIS - in it at least sometimes I write more code, but such surprises do not occur ...

**Comment by dmex** [comment]
```
procedure CurStepChanged (CurStep: TSetupStep);
var
  iResultCode: Integer;
begin
  if CurStep = ssInstall then begin
    if IsServiceRunning ('KProcessHacker2') then
      StopService ('KProcessHacker2');
   if IsTaskSelected ('delete_KPH_service') then
      RemoveService ('KProcessHacker2');
    if IsServiceRunning ('KProcessHacker3') then
      StopService ('KProcessHacker3');
  end;
```

RemoveService... KProcessHacker**3** ?

**Comment by VictorVG** [comment]
In the original code was, now I removed this place and added delays after running the command scm stop kph3 after which the driver status check via SCM follows. I put two cycles of such checks with the difference in waiting time - the first 3 seconds, the second 8. And if after the second scm does not confirm to us that the driver is stopped, then we will display MsgBox about the need to restart the OS. The driver will only be updated when it becomes possible - in to [Files] section I add flags _replacesameversion overwritereadonly restartreplace_

```
Source: "..\..\KProcessHacker\bin-signed\i386\kprocesshacker.sys" ; DestDir: "{app}"; Flags: ignoreversion replacesameversion overwritereadonly restartreplace; Check: not Is64BitInstallMode()
Source: "..\..\KProcessHacker\bin-signed\amd64\kprocesshacker.sys"; DestDir: "{app}"; Flags: ignoreversion replacesameversion overwritereadonly restartreplace; Check: Is64BitInstallMode()
```
and rewrite in [Code] section:
```
procedure CurStepChanged(CurStep: TSetupStep);
var
  iResultCode: Integer;
begin
  if CurStep = ssInstall then begin
    if IsServiceRunning('KProcessHacker2') then
      StopService('KProcessHacker2');
    if IsTaskSelected('delete_KPH_service') then
      RemoveService('KProcessHacker2');
    if IsServiceRunning('KProcessHacker3') and IsTaskSelected('create_KPH_service') and IsUpgrade() then begin
      StopService('KProcessHacker3');
      Sleep(3000);
    if not IsServiceStopped('KProcessHacker3') then begin
      Sleep(8000);
      if not IsServiceStopped('KProcessHacker3') then
       MsgBox('Reboot required for update kernel-mode driver.', mbInformation, MB_OK);
       end;  
      end;
   end;
```
and added in to Services_Full.iss new check (small :) )

```
function IsServiceStopped(ServiceName: String): Boolean;
var
  hSCM     : HANDLE;
  hService : HANDLE;
  Status   : SERVICE_STATUS;
begin
  hSCM   := OpenServiceManager();
  Result := False;
  if hSCM <> 0 then begin
    hService := OpenService(hSCM, ServiceName, SERVICE_QUERY_STATUS);
    if hService <> 0 then begin
      if QueryServiceStatus(hService, Status) then begin
        Result := (Status.dwCurrentState = SERVICE_STOPPED);
      end;
      CloseServiceHandle(hService);
    end;
    CloseServiceHandle(hSCM);
  end;
end;
```
I wanted to update the SHA1 driver before the update operation so that if the driver did not change, then I did not update it, but Inno Setup became stubborn and began to swear that I had incorrectly set the parameters of the scan function. And besides the description of the prototype GetSHA1OnFile (), there is nothing nowhere. Therefore, I postponed this idea "for later" - at the time of launch I get infinite errors of the runtime that the path / file is not found, but I do not know how to set them correctly in this function.:)

In the end it turned out this way: [installer.zip](https://github.com/processhacker2/processhacker/files/1550271/installer.zip)

And here's what failed - on this code I got out errors: [Inno Setup.zip](https://github.com/processhacker2/processhacker/files/1550279/Inno.Setup.zip) . :(

**Comment by VictorVG** [comment]
v3.0.5655.1128 - I rewrite installer code and added check fo _Stop pending_ driver status, but problem is exists in to Windows 7 - Win 10, and respond using any management tools: Windows Services API, Far Manager plugin SvcMgr (Service Manager), console command, [**Pserv4**](http://p-nand-q.com), any installer. My current variant's installer code is:

Services.iss
```
function IsServiceStopPending(ServiceName: String): Boolean;
var
  hSCM     : HANDLE;
  hService : HANDLE;
  Status   : SERVICE_STATUS;
begin
  hSCM   := OpenServiceManager();
  Result := False;
  if hSCM <> 0 then begin
    hService := OpenService(hSCM, ServiceName, SERVICE_QUERY_STATUS);
    if hService <> 0 then begin
      if QueryServiceStatus(hService, Status) then begin
        Result := (Status.dwCurrentState = SERVICE_STOP_PENDING);
      end;
      CloseServiceHandle(hService);
    end;
    CloseServiceHandle(hSCM);
  end;
end;
```
installer code added:
[Setup]
PrivilegesRequired=admin
CloseApplications=yes

[Files]
Source: "..\..\KProcessHacker\bin-signed\i386\kprocesshacker.sys" ; DestDir: "{app}"; Flags: ignoreversion replacesameversion overwritereadonly restartreplace; Check: not Is64BitInstallMode()
Source: "..\..\KProcessHacker\bin-signed\amd64\kprocesshacker.sys"; DestDir: "{app}"; Flags: ignoreversion replacesameversion overwritereadonly restartreplace; Check: Is64BitInstallMode()

```
[Code]
function NeedRestart(): Boolean;
begin
    Result := False;
    if IsServiceStopPending('KProcessHacker3') then
    Result := True;
end;   
...........
procedure CurStepChanged(CurStep: TSetupStep);
var
  iResultCode: Integer;
begin
  if CurStep = ssInstall then begin
    if IsServiceRunning('KProcessHacker2') then
      StopService('KProcessHacker2');
    if IsTaskSelected('delete_KPH_service') then
    begin
      StopService('KProcessHacker2');
      StopService('KProcessHacker3');
      RemoveService('KProcessHacker2');
      RemoveService('KProcessHacker3');    
    end;
    if IsServiceRunning('KProcessHacker3') then
    begin
    StopService('KProcessHacker3');
    Sleep(1500);
    NeedRestart();
   end;
  end;
```
I try added additional pause before next status check - driver status is _Stop pending_ , Service Control Manager returned error 1053 (ERROR_SERVICE_REQUEST_TIMEOUT). All driver handles is close, driver not used, just wait unknown external events and not stopped...

Latest my working instller code - [installer.zip](https://github.com/processhacker2/processhacker/files/1558173/installer.zip).

**Comment by VictorVG** [comment]
Compiled 3.0.5656.1129, checked, put in the end displays a message about the need to reboot, check the driver and SCM reports the driver hangs with the reason:

ServiceName: KProcessHacker3
         Type: 1 KERNEL_DRIVER
         Status: 3 STOP_PENDING
                                 (STOPPABLE, NOT_PAUSABLE, IGNORES_SHUTDOWN)
         Win32 exit code: 0 (0x0)
         Service_Service_Code: 0 (0x0)
         Control_point: 0x0
         Waiting: 0x0

[SC] ControlService: error: 1061:

The service is currently unable to receive commands.

Also I use for test https://ci.appveyor.com/api/projects/processhacker/processhacker2/artifacts/processhacker-3.0.1128-setup.exe - result:

![kph3](https://user-images.githubusercontent.com/906886/33995239-66c3c796-e0ee-11e7-9532-9b8ba1098de8.png)
![kph3status](https://user-images.githubusercontent.com/906886/33995240-66f57d0e-e0ee-11e7-835a-083638822c21.png)

As a result, you will have to restart three machines and the average operating time of the OS - until the next driver installation, and taking into account the search for a workaround for the error of its hangup, this is 15-20 minutes. An error in the driver, and most likely it was brought by Microsoft the next curve SDK as well as in people with Win10 1607, 1709 the probability of driver hangup when stopped was the same 1: 3 - 1: 2 as the stars in the sky converge ...

**Comment by dmex** [comment]
What software do you have installed?

> you will have to restart three machines

You're the only person that has this problem with the driver... nothing has changed.

**Comment by VictorVG** [comment]
Stop, stop! It seems I understand what's the matter - from the server system squeaks McAfee and has access protection enabled. And in theory this may be a manifestation of her work - she should also prevent unauthorized changes to the OS, and changing the mode of the driver from its point of view should look like this, and so it should work. Am I right in reasoning?

I'm just used to the fact that McAfee VirusScan Enterprise for Linux is deployed on the server, which protects the entire network and does not pay attention to it, and access protection as described by McAfee just blocks unauthorized interference in the configuration and operation of the OS and if this is the result of its operation, then after its setting will resolve the problem. I'll go take the guys docks on this antivirus because ClamAV installed by me does not have such protection and its daemon does not interfere with the drivers work as it was designed primarily for working with mail and network connections and blocks the infection not inside the OS, but at the entrance to it .

**Comment by VictorVG** [comment]
I rewrited section CODE and add SHA1 check for driver - then my problem is fixed. The truth required to spend a lot of work, but now you only need to think how to make the preprocessor (ISPP) generate constants for checking, well, it does not work out - you'll have to use the old-fashioned, pens. :)

I add to code new function:
```
function IsUpdKPH(): Boolean;
var
   x86: String;
   x64: String;

begin
   x86 := '5452339315254a3b7f236a10c3d1ce09d04131e3';
   x64 := '624a63232e0acc4992ce01f3e836711e4f6da2f1';

   if Is64BitInstallMode() then
   Result := (GetSHA1OfFile(ExpandConstant('{app}\kprocesshacker.sys')) <> x64)
   else
   Result := (GetSHA1OfFile(ExpandConstant('{app}\kprocesshacker.sys')) <> x86);
end;

............................

function NeedRestart(): Boolean;
begin
    Result := False;
    if IsServiceStopPending('KProcessHacker3') then
    Result := True;
end;   

..................................

procedure CurStepChanged(CurStep: TSetupStep);
var
  iResultCode: Integer;
begin
  if CurStep = ssInstall then begin
    if IsUpdKPH() and IsServiceRunning('KProcessHacker3') then
    begin
    StopService('KProcessHacker3');
    Sleep(1500);
    NeedRestart();
    end;
    if IsTaskSelected('delete_KPH_service') then
    begin
      StopService('KProcessHacker2');
      StopService('KProcessHacker3');
      RemoveService('KProcessHacker2');
      RemoveService('KProcessHacker3');    
    end;
   end;
````
and fix  this problem, bun don't know source ....

**Comment by VictorVG** [comment]
[**Workaround**]9https://wj32.org/processhacker/forums/viewtopic.php?f=5&p=9361#p9361) - refactoring and rewrite. Diff:
```
--- Process_Hacker_installer_full.iss	Wed Dec 13 23:19:44 2017
+++ Process_Hacker_installer_full.iss	Tue Dec 19 02:41:30 2017
@@ -19,16 +19,13 @@
 ;* You should have received a copy of the GNU General Public License
 ;* along with Process Hacker. If not, see <http://www.gnu.org/licenses/>.
 ;
-; Last updated 13.12.2017 23:19:41 +0300 VictorVG @ VikSoft.Ru
-; update script version up to v14.0.55 (non oficial).
+; Last updated 19.12.2017 02:41:28 +0300 VictorVG @ VikSoft.Ru
+; update script version up to v14.0.60 (non oficial).
 ;
 ; Requirements:
 ; *Inno Setup: http://www.jrsoftware.org/isdl.php
 ;
-; WARNING:
-;
-; Driver name KProcessHacker2 in to [Code] section does not change or the program
-; will fail!
+; Thanks Genri on forum.ru-board.con on help.
 ;
 #if VER < EncodeVer(5,5,9)
   #error Update your Inno Setup version (5.5.9 or newer)
@@ -40,7 +37,7 @@
 #include "Custom_Messages_Full.iss"
 #include "Services_Full.iss"
 
-#define installer_build_number "14.0.55"
+#define installer_build_number "14.0.60"
 #define copyright              "Copyright © 2010-2017, Process Hacker Team. Licensed under the GNU GPL, v3.0"
 #define website_url            "http://processhacker.sourceforge.net/"
 #if defined(TWO_DIGIT_VER)
@@ -56,6 +53,7 @@
 #define installer_build_date   GetDateTimeString('mmm, d yyyy', '', '')
 #define quick_launch           "{userappdata}\Microsoft\Internet Explorer\Quick Launch"
 
+
 [Setup]
 AppID=Process_Hacker
 AppCopyright={#copyright}
@@ -193,8 +191,8 @@
 Source: "..\..\bin\Release32\ProcessHacker.sig"; DestDir: "{app}";     Flags: ignoreversion onlyifdoesntexist; Check: not Is64BitInstallMode()
 Source: "..\..\bin\Release32\ProcessHacker.sig"; DestDir: "{app}\x86"; Flags: ignoreversion onlyifdoesntexist; Check: Is64BitInstallMode()
 
-Source: "..\..\KProcessHacker\bin-signed\i386\kprocesshacker.sys" ; DestDir: "{app}"; Flags: ignoreversion replacesameversion overwritereadonly restartreplace; Check: not Is64BitInstallMode()
-Source: "..\..\KProcessHacker\bin-signed\amd64\kprocesshacker.sys"; DestDir: "{app}"; Flags: ignoreversion replacesameversion overwritereadonly restartreplace; Check: Is64BitInstallMode()
+Source: "..\..\KProcessHacker\bin-signed\i386\kprocesshacker.sys" ; DestDir: "{app}"; Flags: ignoreversion replacesameversion overwritereadonly restartreplace; Check: IsKph32()
+Source: "..\..\KProcessHacker\bin-signed\amd64\kprocesshacker.sys"; DestDir: "{app}"; Flags: ignoreversion replacesameversion overwritereadonly restartreplace; Check: IsKph64()
 
 Source: "..\..\plugins-extra\TerminatorPlugin\resources\kprocesshacker2_x32.sys"; DestDir: "{app}\plugins\plugindata"; Flags: ignoreversion; Check: not Is64BitInstallMode()
 Source: "..\..\plugins-extra\TerminatorPlugin\resources\kprocesshacker2_x64.sys"; DestDir: "{app}\plugins\plugindata"; Flags: ignoreversion; Check: Is64BitInstallMode()
@@ -374,6 +372,8 @@
   installer_mutex = 'process_hacker_setup_mutex';
   IFEO            = 'SOFTWARE\Microsoft\Windows NT\CurrentVersion\Image File Execution Options\taskmgr.exe';
   HKCURUN         = 'Software\Microsoft\Windows\CurrentVersion\Run';
+  x86             = '{#GetSHA1OfFile("..\..\KProcessHacker\bin-signed\i386\kprocesshacker.sys")}';
+  x64             = '{#GetSHA1OfFile("..\..\KProcessHacker\bin-signed\amd64\kprocesshacker.sys")}'; 
 
 
 function IsUpgrade(): Boolean;
@@ -385,6 +385,7 @@
 end;
 
 
+// if driver status is SERVICE_STOP_PENDING set reboot flag
 function NeedRestart(): Boolean;
 begin
     Result := False;
@@ -393,6 +394,41 @@
 end;   
 
 
+// Check for driver needed copy 
+function IsCpyKPH(): Boolean;
+begin
+ if not IsTaskSelected('create_KPH_service') then
+  if IsUpgrade() then begin
+   if FileExists(ExpandConstant('{app}\kprocesshacker.sys')) then begin
+    if Is64BitInstallMode() then 
+    Result := (GetSHA1OfFile(ExpandConstant('{app}\kprocesshacker.sys')) <> x64)
+    else
+    Result := (GetSHA1OfFile(ExpandConstant('{app}\kprocesshacker.sys')) <> x86)
+    end else
+    Result := IsServiceInstalled('KProcessHacker3');
+    end else
+    Result := True;
+end;
+
+
+// Check for x86 driver needed copy 
+function IsKph32(): Boolean;
+begin
+  if IsCpyKPH() then
+   if not Is64BitInstallMode() then
+   Result := True;
+end;
+
+
+// Check for x64 driver needed copy
+function IsKph64(): Boolean;
+begin
+  if IsCpyKPH() then
+   if Is64BitInstallMode() then
+   Result := True;
+end;
+
+
 function ShouldSkipPage(PageID: Integer): Boolean;
 begin
   // Hide the License and the Ready to install page if it's an upgrade
@@ -470,26 +506,28 @@
     WizardForm.NextButton.Caption := SetupMessage(msgButtonInstall);
 end;
 
-
 procedure CurStepChanged(CurStep: TSetupStep);
 var
   iResultCode: Integer;
 begin
   if CurStep = ssInstall then begin
-    if IsServiceRunning('KProcessHacker2') then
-      StopService('KProcessHacker2');
-    if IsTaskSelected('delete_KPH_service') then
-    begin
+    if IsServiceInstalled('KProcessHacker3') then begin
+     if IsCpyKPH() then
+      if IsServiceRunning('KProcessHacker3') then begin
+       StopService('KProcessHacker3');
+       Sleep(800);
+      if not IsServiceStopped('KProcessHacker3') then begin 
+       Sleep(2200);
+       NeedRestart();
+      end;
+     end;
+    end;
+    
+   if IsTaskSelected('delete_KPH_service') then begin
       StopService('KProcessHacker2');
       StopService('KProcessHacker3');
       RemoveService('KProcessHacker2');
       RemoveService('KProcessHacker3');    
-    end;
-    if IsServiceRunning('KProcessHacker3') then
-    begin
-    StopService('KProcessHacker3');
-    Sleep(1500);
-    NeedRestart();
    end;
   end;
 
--- Services_Full.iss	Tue Dec 19 11:21:19 2017
+++ Services_Full.iss	Mon Dec 18 23:47:31 2017
@@ -197,4 +197,64 @@
     end;
     CloseServiceHandle(hSCM);
   end;
+end;
+
+
+function IsServiceStopPending(ServiceName: String): Boolean;
+var
+  hSCM     : HANDLE;
+  hService : HANDLE;
+  Status   : SERVICE_STATUS;
+begin
+  hSCM   := OpenServiceManager();
+  Result := False;
+  if hSCM <> 0 then begin
+    hService := OpenService(hSCM, ServiceName, SERVICE_QUERY_STATUS);
+    if hService <> 0 then begin
+      if QueryServiceStatus(hService, Status) then begin
+        Result := (Status.dwCurrentState = SERVICE_STOP_PENDING);
+      end;
+      CloseServiceHandle(hService);
+    end;
+    CloseServiceHandle(hSCM);
+  end;
+end;
+
+
+function IsServiceStopped(ServiceName: String): Boolean;
+var
+  hSCM     : HANDLE;
+  hService : HANDLE;
+  Status   : SERVICE_STATUS;
+begin
+  hSCM   := OpenServiceManager();
+  Result := False;
+  if hSCM <> 0 then begin
+    hService := OpenService(hSCM, ServiceName, SERVICE_QUERY_STATUS);
+    if hService <> 0 then begin
+      if QueryServiceStatus(hService, Status) then begin
+        Result := (Status.dwCurrentState = SERVICE_STOPPED);
+      end;
+      CloseServiceHandle(hService);
+    end;
+    CloseServiceHandle(hSCM);
+  end;
+end;
+
+
+function IsServiceInstalled(ServiceName: string) : boolean;
+var
+	hSCM	: HANDLE;
+	hService: HANDLE;
+begin
+	hSCM := OpenServiceManager();
+	Result := false;
+	if hSCM <> 0 then begin
+		hService := OpenService(hSCM,ServiceName,SERVICE_QUERY_CONFIG);
+        if hService <> 0 then begin
+            Result := true;
+            CloseServiceHandle(hService)
+		end;
+        CloseServiceHandle(hSCM)
+	end
 end;
\ No newline at end of file
```
