### ISSUE TITLE
Can't build PH with MS VS 2017 v15.5.0

### ISSUE THREAD

**Issue by skipik** [processhacker2/processhacker#198]
I'm getting this:

error MSB8036: The Windows SDK version 10.0.16299.0 was not found. Install the required version of Windows SDK or change the SDK version in the project property pages or by right-clicking the solution and selecting "Retarget solution".

Everything was fine on v15.4.5 though.

- upd

Got it sorted. MS broke something in the latest update. I had to uncheck and check again WinSDK via VS installer.

**Comment by dmex** [comment]
> MS broke something in the latest update

They broke more than the SDK in the latest update 😄
