### ISSUE TITLE
De-couple 'Help --> About' and main window

### ISSUE THREAD

**Issue by stdedos** [processhacker2/processhacker#201]
I am unable to otherwise change the status of main window if About is open.

Trying to set is as "not Always on top" (so I can open e.g. the browser to write the PH version from the About window), also passes "Always On Top" flag to the About window (which can then be superseeded by an "Always On Top" window)

**Comment by dmex** [comment]
> which can then be superseeded by an "Always On Top" window

Not sure what this means?

**Comment by stdedos** [comment]
> > which can then be superseeded by an "Always On Top" window

> Not sure what this means?

If you have two 'Always On Top' windows, you can change between the two.
If you cancel one's 'Always On Top' property, then (obviously) you cannot see it anymore.

The issue here is that, if you cancel PH's 'Always On Top', then settings might get messed up in the settings.

That ^^ comment was mostly driven by the "use scenario" that I had in front of me. (maybe not useful in hindsight)

This feature also helps to e.g. hide PH while still keep 'About' open for other uses, move the main window "out of the way"

**Comment by stdedos** [comment]
Thank you for the change

So, what is your process? Do I close it or you?
