### ISSUE TITLE
no Automatic delayed in service properties

### ISSUE THREAD

**Issue by tigros** [processhacker2/processhacker#203]
Hi,

I was working on a service program and noticed 2 things, there's no Automatic delayed in service properties, that an important one since some services don't work without it, like mine for example :) (it sends emails so...)

Also if I change the startup type in services.msc there's no way to get it to update in PH without restarting PH it seems.

oh and a third thing, if it fails to set startup type the Retry/Cancel popup doesn't seem to retry just closes.

here's to making PH better, cheers!

**Comment by dmex** [comment]
> Automatic delayed in service

You mean this?
https://i.imgur.com/AlFDis3.png

**Comment by tigros** [comment]
ha ok thx didn't look all the way down there.. lol

**Comment by dmex** [comment]
I have a plugin that does the same thing using kernel ETW events (without a driver) but haven't had the time to clean it up and commit it... I'll try get around to it soon.
