### ISSUE TITLE
Performance Issue

### ISSUE THREAD

**Issue by stdedos** [processhacker2/processhacker#209]
I might have an issue, although, I don't know how to debug it:

On a Pentium 4 / Windows 8.1 / 80GB HDD / Stable PH, having the window open shows ~25% usage for PH
*The PC is pretty old, obviously, no doubt about that*

**Comment by dmex** [comment]
Try changing the following settings:

EnableCycleCpuUsage: 0
EnableServiceNonPoll: 0
EnableServiceStage2: 0
EnableStage2: 0

**Comment by stdedos** [comment]
For the first couple of minutes it settled on ~17-23%.
Changing refresh to 1s toned it down to ~13-17%

Closing it on tray, after a while it settled to a whopping ~1-3% (with 0.5s and open to 6.25-7.81%)

If you wouldn't like any "performance data" coming, go ahead and close it.
Otherwise, I am more than satisfied 😄
