### ISSUE TITLE
Some suggestions

### ISSUE THREAD

**Issue by freesoft0000** [processhacker2/processhacker#211]
Process Label:
Right-click Properties-General information, missing file size, creation time, modification time, access time. Property information such as read-only, system, hide, and so on.

Service Label:
It is recommended that you increase the right key to change the startup type of the setup item. And can be changed in bulk after multiple service selections.

The settings for the current startup state cannot be changed in bulk, and it is recommended that you change the batch changes to multiple selections.

Right-click Property, where the label page has no general information about the file, and the general information should be the same as in the Process tab.

Network Label:
The process PID list is missing. End process and bulk end process missing

Disk Label:
Running the 32-bit process Hacker in a 64-bit system, the file path is incorrect and the box appears. Running the 6-bit process hacker appears normal.

**Comment by freesoft0000** [comment]
![32](https://user-images.githubusercontent.com/30435921/34318609-958bcf68-e807-11e7-9876-aae65fc9f331.png)

**Comment by dmex** [comment]
> Right-click Properties-General information, missing file size, creation time, modification time, access time. Property information such as read-only, system, hide, and so on.

These are NTFS file attributes not process information.

> Network Label: The process PID list is missing.

The network tab shows the PID in brackets after the process name,

> Running the 32-bit process Hacker in a 64-bit system, the file path is incorrect

The undocumented native API doesn't support wow64 processes.
