### ISSUE TITLE
Sometimes horizontal scrollwheel doesn't scroll treeview

### ISSUE THREAD

**Issue by starkeyvsk** [processhacker2/processhacker#216]
I get this a lot. 

The scrollbar in the UI will move, but the actual tree view columns to the right of the fixed name column don't move.

I tried this with the debugger attached and when it happens, the treenew's WM_MOUSEHWHEEL message case doesn't even get triggered, but if I put the mouse over the scrollbar part of the UI, it does.

**Comment by dmex** [comment]
I can't reproduce this on any of my machines.

What mouse device/driver do you have installed?

**Comment by eugenesvk** [comment]
I get the same issue with Logitech MX anywhere mouse and setpoint drivers.

Another issue is that when scroll right is working the scroll indicator moves before the view is updated

https://github.com/user-attachments/assets/768610e1-23a3-4f45-9b63-b609db05e5ae

Compare this to my custom Autohotkey Shift+WheelUp/Down fuction that sends horizontal scroll events (though don't remember which API/input method of sending scroll events it's using by default). Here it's all smooth and as expected - the view and the bar move in "steps"

https://github.com/user-attachments/assets/101a1f90-4845-47b2-b3b4-bdeacf6bea90
