### ISSUE TITLE
accessible checkboxes (request)

### ISSUE THREAD

**Issue by botmtl** [processhacker2/processhacker#218]
could you link the checkboxes to their description in the options? (selecting description + spacebar already works but mouse integration would be nice).
![acessible_checkbox](https://user-images.githubusercontent.com/7614617/34547382-c75272c6-f0c8-11e7-8228-6c62c9f3e2b5.gif)

**Comment by dmex** [comment]
I've added click support but not double click support. Can you try the latest nightly and let me know if its working as expected (or needs double click support)?

**Comment by ge0rdi** [comment]
After this change single click to check-box (actual _box_ part) doesn't work.
Single click to check-box' text works as expected.

**Comment by dmex** [comment]
@ge0rdi 

Should be fixed now 😄

**Comment by ge0rdi** [comment]
I can confirm that it works well now.

**Comment by botmtl** [comment]
Thank you!  works great.
