### ISSUE TITLE
The latest version canceled the process of injection?

### ISSUE THREAD

**Issue by stonedreamforest** [processhacker2/processhacker#223]

**Comment by stonedreamforest** [comment]
I saw it：
![tim 20180109202419](https://user-images.githubusercontent.com/16742566/34720807-1a24b5de-f57b-11e7-9ae1-b35176113a4a.png)

I don't know why you want to delete it,It is a very handy and useful feature.

**Comment by TETYYS** [comment]
I suppose because of VAC complaints
