### ISSUE TITLE
v3.0.5766.1239  Menu View :: Tray icons error item index for "Network usage (Text)"

### ISSUE THREAD

**Issue by VictorVG** [processhacker2/processhacker#228]
Menu View :: Tray icons - display item "Network usage (Text)" in to tray replaced to item "Network history".

**Comment by dmex** [comment]
English?

**Comment by VictorVG** [comment]
In to menu selected _Network usage (text)_ icon, but display _Network history_ icon:

![exist](https://user-images.githubusercontent.com/906886/35397114-ac623936-01ff-11e8-8a38-14659d107bd7.png)

**Comment by dmex** [comment]
> http://forum.ru-board.com/topic.cgi?forum=5&topic=49036&start=1500#18

> то слетает фокус на выбранном потоке. Раньше не замечал такого, баг\фича? 

This is a new feature. Do you want the the selection to always remain even when the window doesn't have focus?

> Network usage (Text) и в трее должна отобразиться иконка 
Использование сети в Мб (цифры), а отображается такая же иконка, что и при выборе 

Fixed. The network usage graph show now correctly show text instead of the graph.

**Comment by VictorVG** [comment]
The first and I also explained, only slightly different words:

"In the first case, this is normal - moving the cursor outside the thread window and should be treated as a"

although, probably if possible, it is worth adding a setting such as "Keep selecting an item in the list before changing it by the user" because it sometimes happens that you need to use several windows at once.

For example, it was possible to understand the reasons for Far's fall due to Access Violation in ProcessSynchroEventW (), which appeared in the subfolder FarHints :: Folders (was not updated since 2013) - I looked through the thread of the plugin in the thread window, simultaneously watched the log and tried to understand the debugger who causes a failure. As a result, the module from the set of used deleted and with it nothing falls, and earlier it happened several times a day. So if it were not for Process Hacker to find the cause of the error, it would have been recommended in the documentation for Far to use the method of enumerating all the scripts and plug-ins. "Fast" operation with almost a hundred plug-ins and two and a half hundreds of scripts. :)

The confusion of icons is fixed, thank you so much!

**Comment by VictorVG** [comment]
Big thanks! I always test it . Ok!
