### ISSUE TITLE
since processhacker-3.0.1239 don't show up the main window, just spawning process and then terminating them.

### ISSUE THREAD

**Issue by ralvarador** [processhacker2/processhacker#229]
Once auto-updated to processhacker-3.0.1239, the processhacker main window never came up again neither the try-icon... even after a restart - doesn't appear a thing.
Processhacker processes are launched then terminated continously.
It's happening in a VirtualBox VM runnig a W10 guest OS (but it isn't happening in the Host OS = W7 Ent.; The process hacker was successfuly updated on it)
Tried with versions: processhacker-3.0.1239 and processhacker-3.0.1241
re-installing the processhacker-3.0.5714.1187 - works again!
[https://i.imgur.com/hSq5BT3.gif](https://i.imgur.com/hSq5BT3.gif) = Installation and behaviour

**Comment by dmex** [comment]
> W10 guest OS

Which version of Windows 10?

**Comment by ralvarador** [comment]
X86, Microsoft Windows10 Pro [Version 10.0.16299.192] / Version 10.0.16299 build 16299

VM running, "Virtualizying" two CPUs, Assigned 4GB (virtual)RAM and using VT-x/AMD-V + Hyper-V as paravitualization.

**Comment by dmex** [comment]
@ralvarador  

Fixed in the latest nightly build 👍
