### ISSUE TITLE
Are you using Virusl Total public API KEY ? 

### ISSUE THREAD

**Issue by BAM0S2** [processhacker2/processhacker#230]
Hello,

I have a knowledge quetion. 
I saw that I can query processes from VirusTotal with ProcessHacker.  
As far as I know, to query Virus Total you need to have API public key.  
Are you using such key or you are parsing the HTML page from Virus Total ?  Because I didn't see a API public key in the code. 

https://github.com/processhacker2/processhacker/blob/60a10900b917e9a03c98b762dbc708df1a2037a3/plugins/OnlineChecks/virustotal.c

**Comment by dmex** [comment]
> As far as I know, to query Virus Total you need to have API public key.

VirusTotal does not require an API key... You can just sent GET requests to their public URLs and get json responses.

https://www.virustotal.com/en/file/upload/?sha256=FILEHASH

For example:
https://www.virustotal.com/en/file/upload/?sha256=5883996a7ec7874bec779acccf3f5e218891438d5d417f0c267c51565882b8be



> you are parsing the HTML page from Virus Total 

The above URL returns a JSON response. You need to copy the "file_exists" and "upload_url" values from the response and if the "file_exists" value is False then do a POST request to the "upload_url". 

After the upload completes you can query the redirect URL to show the results page (or just use a hard-coded page like we do): https://www.virustotal.com/en/file/FILEHASH/analysis/

For example:
https://www.virustotal.com/en/file/5883996a7ec7874bec779acccf3f5e218891438d5d417f0c267c51565882b8be/analysis/
