### ISSUE TITLE
Unexpected loss of handle binding  to the file name

### ISSUE THREAD

**Issue by leo-yuriev** [processhacker2/processhacker#232]
It is really strange situation.

I see some program is blocked inside WriteFile() function, i.e. actually inside ZwWriteFile().
The handle is not a pipe, not a COM/LPT, but just the valid local file.
So, no reason WriteFile() to be blocked... Seems this is a bug in the kernel due multithred collision between LockFileEx() and WriteFile() in a single process.

But when such deadlock occures Process Hacker don't show the corresponded file name of the handle.

**Comment by leo-yuriev** [comment]
Seems this is a Windows kernel bug, but not Process Hacker.

First thread:
```
nt!KiSwapContext+0x7a
nt!KiCommitThreadWait+0x1d2
nt!KeWaitForSingleObject+0x19f
nt!IopSynchronousServiceTail+0x2a9
nt!NtLockFile+0x514
nt!KiSystemServiceCopyEnd+0x13
0x77bee1ea
```

Second thread:
```
nt!KiSwapContext+0x7a
nt!KiCommitThreadWait+0x1d2
nt!KeWaitForSingleObject+0x19f
nt!IopAcquireFileObjectLock+0x84
nt! ?? ::NNGAKEGL::`string'+0x491d5
nt!KiSystemServiceCopyEnd+0x13
0x77bed43a
```
But no reason to IopAcquireFileObjectLock() be blocked.

**Comment by leo-yuriev** [comment]
Sure this is a Windows kernel bug.
https://gist.github.com/leo-yuriev/b25697898a754dbaa0dac89abf824a72

**Comment by dmex** [comment]
> when such deadlock occures Process Hacker don't show the corresponded file name of the handle

The documented GetMappedFileName function would also be affected. If you can update your gist to show GetMappedFileName failing under these conditions then I could forward the details to MS?

**Comment by leo-yuriev** [comment]
All functions that attempt to use the locked handle as a FileObject will be affected (via IopAcquireFileObjectLock).

So I prefer to keep the gist as simple as possible.
