### ISSUE TITLE
False positive Current Nightly Feb 6th 2018 

### ISSUE THREAD

**Issue by DarkJester** [processhacker2/processhacker#237]
Hey all,

the current nightly proccesshacker-3.0.1301-setup.exe 
SH2 A5365BA9388CF39B144604E767FA7376805CD4A5CADD9AACCDF4A8833AE308CB

its detected as,
Trojan:Win32/Fuery.A!cl

By windows defender

**Comment by dmex** [comment]
You need to update the windows defender signature definitions 👍

**Comment by ralvarador** [comment]
I just want add something...
You should talk with the People from Sophos AV...  the whole set of PH 3.x installers is detected as a virus (and - sometimes, the PANDA AV FREE does it): 
20180207 082919	Utilizando datos de detección versión 5.47 (motor de detección 3.70.2). Esta versión puede detectar 15461683 elementos.
20180207 090154	Archivo "C:\Users\XXXXXXXXX\AppData\Local\process hacker\Cache\mbhzrjkkexvhput\processhacker-3.0.1301-setup.exe" pertenece al **adware/PUA 'Generic PUA ED'** (del tipo Otro).
