### ISSUE TITLE
search on modules and threads

### ISSUE THREAD

**Issue by heforfree** [processhacker2/processhacker#29]
can we have search feature on
properties modules and threads tabs/

**Comment by dmex** [comment]
Do you mean each window having its own search or expanding the 'Find handles and dlls" window to concurrently search the modules and threads tab of every process?

**Comment by heforfree** [comment]
example i get properties of firefox.exe then in modules and threads tab have search feature like ctrl+k in main window

**Comment by dmex** [comment]
I've added search to some process properties pages in the nightly builds:
https://wj32.org/processhacker/nightly.php

**Comment by heforfree** [comment]
thanks much appreciated.this is a exactly what i wanted.
i just now available in handles(not search-able in "name,granted access" header ),window tab.
memory,modules and threads tabs need this too.
thanks best regards

**Comment by dmex** [comment]
@heforfree 

- [ ] Handle tab search.
- [ ] Window tab search.
- [ ] Memory tab search.
- [ ] Module tab search.
- [ ] Threads tab search.

Slowly getting there...
