### ISSUE TITLE
UI: Process aggregation: Display count

### ISSUE THREAD

**Issue by prasannavl** [processhacker2/processhacker#6]
When the UI is set to aggregate CPU, memory etc, for the processes in the sub-tree, it would be very helpful it shows a count of the number of processes in the sub-tree when it is collapsed (and only when its collapsed).

**Example case 1:** _When there are no subprocesses to the subprocesses in the tree_:

Instead of just a collapsed `chrome.exe`, it would display `chrome.exe (10)`, if it has a total of 10 processes, including its sub-processes. 

**Example case 2:** _When there are subprocesses to the subprocesses_:

Instead of just a collapsed `explorer.exe`, it would display `explorer.exe (10, 25)`, if it has a total of 10 direct subprocesses, but a total of 25 including the subprocesses of every subprocess tree (recursively).

Thoughts?

**Comment by dmex** [comment]
It would require keeping a duplicate copy of the unmodified original string resulting in 2x the memory usage and later switching the strings on the fly (which can result in an access violation due to message loop reentry).

As an alternative just add the 'selected' item to the Statusbar and select the group to determine the number of items.

**Comment by prasannavl** [comment]
Perhaps, a separate column "No of children" instead that uses a similar logic as specified above? That way, whoever finds it useful can keep the column, or don't need to use it when it's not. This also has the added advantage of avoiding the "selected" processes calculation unless the column is in explicitly chosen.

**Comment by dmex** [comment]
How does knowing the number of processes in a 'group' have any practical benefits?

For example if we implemented this feature... "cool there's 10 chrome processes" now what? you don't gain anything by knowing that number and you can't do anything with that because on Windows there are no differences between 10 chrome processes or 100 chrome processes.

If you can show how knowing the number of processes in a group would be useful information then I'll reopen the ticket.

**Comment by prasannavl** [comment]
@dmex, I think if we go down that path of ideologies - there are many things that are far more useless than a count.

That being said, a count would be very useful to see whether or not a new process has spun up in a group, when you want to glance it without switching the tree back and forth. Long story short - it helps me identify rouge processes in a group that overstay their welcome by not exiting for longer, or quickly know if a process metrics remain as expected in certain known condition. Now, while the obvious question is why to keep in collapsed in that case - process proliferation has become quite common, and there are tons of processes in a system these days - Chrome, VSCode, SvcHost for example. Expanding them becomes painful on laptops with small screens, and hinders the overall view. 

Or may be, sometimes, I may want to corelate the total amount of memory, and CPU usage with the count of the children. 

A lot of these metrics won't really be very useful - until it is. Take Subsystem, for example which btw, doesn't include WSL, and such - just purely Windows or Windows Console - are they really any practical benefits of knowing here? Or take even Cycles count. If we look down with that line of thought, does Cycle count really add any value? Does any one really care? Sure cycle delta could be useful in knowing if there are changes - but a lot of these base ideas will be conveyed by CPU usage, and CPU history anyway. 

I think in softwares like process hacker, sticking strictly to the solid use scenario may not always be the best approach - since there's no one answer to why a certain metric might be useful over the other - except in a certain resource-triage scenario, perhaps.

**Comment by dmex** [comment]
I've added the "Subprocesses" column for showing the number of process children:
http://i.imgur.com/11T0Y4b.png

It's available in the latest nightly build 👍 
https://wj32.org/processhacker/nightly.php

**Comment by prasannavl** [comment]
That was fast. I was planning on submitting a PR this weekend after the
discussion on the issue. You beat me to it! Taking it for a test drive -
every looks perfect so far. Thanks :)

**Comment by dmex** [comment]
I just pushed a new nightly release that fixes the subprocesses column sorting and you can now sort the column 👍 

> Take Subsystem, for example which btw, doesn't include WSL, and such - just purely Windows or Windows Console

That bug has also been fixed and WSL is now identified as POSIX.

**Comment by prasannavl** [comment]
@dmex - Fantastic! However, it doesn't include subprocesses while collapsed though. I feel that kinda defeats the purpose - and it should work along with the "Options" that specifies if CPU, and such should be aggregated.

**Comment by dmex** [comment]
That's a separate issue related to #99 and it'll be fixed when that issue also get fixed 👍
