### ISSUE TITLE
Feature Request: selectable decimal or hex process ID's

### ISSUE THREAD

**Issue by AaronNGray** [processhacker2/processhacker#67]
Can we have a sector for display of decimal and hexadecimal process ID's in the Process Hackers - Find Handles or DLL's. And similar section in the main window. via selection on the column header.

**Comment by AxDSan** [comment]
+1, this would be handy-dandy and a nice feature :+1:

**Comment by dmex** [comment]
Hexadecimal is reserved for pointer addresses and the ProcessID is not a pointer. Why do you need those details as hexadecimal when they're not pointers to memory?

You can install the HexPidPlugin and add the extra column to show PIDs on the process tree as hexadecimal:
https://github.com/processhacker2/plugins-extra/releases

**Comment by AaronNGray** [comment]
Cuz I like Hex over decimal for all things CPU related as its easier on the
memory than decimal when moving between things ;)

**Comment by dmex** [comment]
I've added a new setting to the nightly build called `ShowHexId` for showing PIDs and TIDs with hexadecimal:
https://wj32.org/processhacker/nightly.php

@AaronNGray 

1) Install or update to the latest nightly build (Help > Check for Updates).
2) Exit Process Hacker (you can't change this setting at runtime)
3) Open the settings file (%appdata%\Process Hacker\settings.xml)
4) Locate the `ShowHexId` setting.
5) Change 0 to 1
6) Restart Process Hacker.

Let me know if it's working as expected... 👍
