### ISSUE TITLE
feature request: add avg queue depth, avg io time and disk busy % to pop-up that shows when you mouse over the disk tray icon

### ISSUE THREAD

**Issue by mailinglists35** [processhacker2/processhacker#78]
![image](https://cloud.githubusercontent.com/assets/2054302/20718677/8bfce916-b66a-11e6-9425-0875c4438097.png)

**Comment by mailinglists35** [comment]
> closed this 16 hours ago

so this mean no... :-1:  :(

**Comment by dmex** [comment]
@mailinglists35 

These options are not consistent with the other popups. If I redesignt he layout of the popup then I'll add these options and others 👍

**Comment by mailinglists35** [comment]
Uhm, there is plenty of free space on that row so I thought it would look ok? Like this:
Disk R: 808 kB W: 0 Q:3 T:15ms B:85% S:64kB
